from typing import Protocol


class ILogger(Protocol):

    @staticmethod
    def _load_env() -> bool: ...

    @staticmethod
    def _create_log_folder(folder_name: str) -> bool: ...

    def _set_const_env_vars(self) -> bool: ...

    def _set_env_vars(self) -> bool: ...

    def _setup(self) -> None: ...

    def log_error(self, message: str) -> None: ...
